# ----------------------------------------------------------------------
# Build MPI-enabled ED2 model with Intel oneAPI
# ----------------------------------------------------------------------
FROM intel/oneapi-hpckit:2023.1.0-devel-ubuntu22.04 AS build

ARG ED2_KIND=E

ENV ED2_KIND=${ED2_KIND}

# Compile HDF5 with Intel compilers. ED2's MPI build uses Intel MPI wrappers,
# while HDF5 collective MPI-IO remains disabled in include.mk.docker.mpi.intel.
RUN wget -q https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.9/src/CMake-hdf5-1.10.9.tar.gz && \
    tar xf CMake-hdf5-1.10.9.tar.gz && \
    cd CMake-hdf5-1.10.9 && \
    sed -e  's/^#*\(.*BUILD_FORTRAN:BOOL=ON.*\)/\1/' \
        -e  's/^#*\(.*BUILD_FORTRAN:BOOL=OFF.*\)/#\1/' \
        -e  's/^#*\(.*intel.cmake.*\)/\1/' \
        -i HDF5options.cmake && \
    ctest -S HDF5config.cmake,BUILD_GENERATOR=Unix,INSTALLDIR=/opt/hdf5 -C Release -V -O hdf5.log && \
    ./HDF5-1.10.9-Linux.sh --skip-license --exclude-subdir --prefix=/opt && \
    cd && \
    rm -rf CMake-hdf5-1.10.9.tar.gz CMake-hdf5-1.10.9

COPY ED       /ED2/ED
COPY RAPP     /ED2/RAPP
COPY Ramspost /ED2/Ramspost

WORKDIR /ED2/ED/build
RUN ./install.sh -k ${ED2_KIND} -g -p docker.mpi.intel
RUN if [ -e ed_*-opt ]; then mv ed_*-opt ed2; else mv ed_*-dbg ed2; fi

########################################################################

# ----------------------------------------------------------------------
# Runtime image with ED2 and Intel MPI
# ----------------------------------------------------------------------
FROM intel/oneapi-hpckit:2023.1.0-devel-ubuntu22.04

WORKDIR /data

COPY --from=build /ED2/ED/build/ed2 /usr/bin/ed2
COPY --from=build /opt/HDF_Group/HDF5/1.10.9 /opt/HDF_Group/HDF5/1.10.9

RUN echo "/opt/HDF_Group/HDF5/1.10.9/lib" > /etc/ld.so.conf.d/hdf5.conf && ldconfig

CMD ["/usr/bin/ed2"]

