#!/usr/bin/env python3
"""Build ED2-ready input files from a staged CSV dataset package."""

from __future__ import annotations

import argparse
import csv
import os
import shutil
import subprocess
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_DIR = REPO_ROOT / "projects" / "data" / "staging_templates"
MONTH_COLUMNS = ("jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec")


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as handle:
        reader = csv.DictReader(handle)
        if not reader.fieldnames:
            raise SystemExit(f"{path} has no CSV header.")
        rows: list[dict[str, str]] = []
        for row in reader:
            cleaned = {str(key).strip().lower(): str(value).strip() for key, value in row.items()}
            if any(cleaned.values()):
                rows.append(cleaned)
    return rows


def first_row(path: Path, required: tuple[str, ...]) -> dict[str, str]:
    if not path.exists():
        raise SystemExit(f"Missing required staging file: {path}")
    rows = read_rows(path)
    if not rows:
        raise SystemExit(f"{path} has no data rows.")
    missing = [name for name in required if name not in rows[0] or rows[0][name] == ""]
    if missing:
        raise SystemExit(f"{path} is missing required columns: {', '.join(missing)}")
    return rows[0]


def optional_rows(path: Path) -> list[dict[str, str]]:
    return read_rows(path) if path.exists() else []


def parse_time(text: str) -> datetime:
    value = text.strip()
    if value.endswith("Z"):
        value = f"{value[:-1]}+00:00"
    parsed = datetime.fromisoformat(value)
    if parsed.tzinfo is None:
        return parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc).replace(tzinfo=timezone.utc)


def nml_time(prefix: str, when: datetime) -> list[str]:
    return [
        f"NL%IMONTH{prefix}  = {when.month:02d}",
        f"NL%IDATE{prefix}   = {when.day:02d}",
        f"NL%IYEAR{prefix}   = {when.year:04d}",
        f"NL%ITIME{prefix}   = {when.hour:02d}{when.minute:02d}",
    ]


def as_int(row: dict[str, str], key: str, default: int) -> int:
    value = row.get(key, "")
    return default if value == "" else int(float(value))


def as_float(row: dict[str, str], key: str, default: float) -> float:
    value = row.get(key, "")
    return default if value == "" else float(value)


def as_text(row: dict[str, str], key: str, default: str = "") -> str:
    value = row.get(key, "").strip()
    return default if value == "" else value


def parse_number_list(text: str) -> list[str]:
    values = [item.strip() for item in text.split(",") if item.strip()]
    if not values:
        raise SystemExit("Expected a comma-separated numeric list.")
    for value in values:
        float(value)
    return values


def nml_list(text: str) -> str:
    return ",".join(parse_number_list(text))


def nml_string(text: str) -> str:
    return "'" + text.replace("'", "''") + "'"


def format_coord(value: str | float) -> str:
    return f"{float(value):.10g}"


def path_for_namelist(path: Path, ed_run_dir: Path, absolute: bool) -> str:
    resolved = path.resolve()
    if absolute:
        return str(resolved)
    return os.path.relpath(resolved, ed_run_dir.resolve())


def write_text(path: Path, text: str, manifest: list[Path]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    manifest.append(path)


def copy_templates(args: argparse.Namespace) -> int:
    args.target.mkdir(parents=True, exist_ok=True)
    copied = 0
    for source in sorted(TEMPLATE_DIR.iterdir()):
        if source.name == "README.md" or source.suffix == ".csv":
            destination = args.target / source.name
            if destination.exists() and not args.force:
                print(f"kept existing {destination}")
                continue
            shutil.copy2(source, destination)
            print(f"wrote {destination}")
            copied += 1
    print(f"template files written: {copied}")
    return 0


def build_domain_fragment(staging: Path, output: Path, region_name: str, manifest: list[Path]) -> dict[str, str]:
    row = first_row(
        staging / "domain.csv",
        ("run_name", "start_time", "end_time", "grid_type", "grid_res", "lat_min", "lat_max", "lon_min", "lon_max"),
    )
    start = parse_time(row["start_time"])
    end = parse_time(row["end_time"])
    n_ed_region = as_int(row, "n_ed_region", 1)
    n_poi = as_int(row, "n_poi", 0)

    lines = [
        "! Generated by scripts/build_ed2_inputs_from_staged.py",
        f"NL%EXPNME = {nml_string(as_text(row, 'run_name', region_name))}",
        *nml_time("A", start),
        *nml_time("Z", end),
        f"NL%N_ED_REGION = {n_ed_region}",
        f"NL%GRID_TYPE = {as_int(row, 'grid_type', 0)}",
        f"NL%GRID_RES = {as_float(row, 'grid_res', 1.0):.10g}",
        f"NL%ED_REG_LATMIN = {as_float(row, 'lat_min', 0.0):.10g}",
        f"NL%ED_REG_LATMAX = {as_float(row, 'lat_max', 0.0):.10g}",
        f"NL%ED_REG_LONMIN = {as_float(row, 'lon_min', 0.0):.10g}",
        f"NL%ED_REG_LONMAX = {as_float(row, 'lon_max', 0.0):.10g}",
        f"NL%N_POI = {n_poi}",
        f"NL%POI_LAT = {as_float(row, 'poi_lat', as_float(row, 'lat_min', 0.0)):.10g}",
        f"NL%POI_LON = {as_float(row, 'poi_lon', as_float(row, 'lon_min', 0.0)):.10g}",
        f"NL%POI_RES = {as_float(row, 'poi_res', as_float(row, 'grid_res', 1.0)):.10g}",
    ]
    write_text(output / "fragments" / "ed2in_domain_fragment.nml", "\n".join(lines) + "\n", manifest)
    return {
        "run_name": as_text(row, "run_name", region_name),
        "met_prefix": as_text(row, "met_prefix", f"{region_name.upper()}_MET_"),
        "start_year": str(start.year),
        "end_year": str(end.year),
        "poi_lat": as_text(row, "poi_lat", as_text(row, "lat_min", "0")),
        "poi_lon": as_text(row, "poi_lon", as_text(row, "lon_min", "0")),
    }


def build_soil_fragment(staging: Path, output: Path, manifest: list[Path]) -> None:
    path = staging / "soil_constants.csv"
    if not path.exists():
        return
    row = first_row(path, ("nzg", "isoilflg", "islcolflg", "nslcon", "slz", "slmstr", "stgoff"))
    slz = parse_number_list(row["slz"])
    slmstr = parse_number_list(row["slmstr"])
    stgoff = parse_number_list(row["stgoff"])
    nzg = as_int(row, "nzg", len(slz))
    if len(slz) != nzg or len(slmstr) != nzg or len(stgoff) != nzg:
        raise SystemExit(f"{path}: slz, slmstr, and stgoff must each contain NZG={nzg} values.")
    lines = [
        "! Generated constant-soil fallback from soil_constants.csv",
        f"NL%NZG = {nzg}",
        f"NL%NZS = {as_int(row, 'nzs', 1)}",
        f"NL%ISOILFLG = {as_int(row, 'isoilflg', 2)}",
        f"NL%ISLCOLFLG = {as_int(row, 'islcolflg', 2)}",
        f"NL%NSLCON = {as_int(row, 'nslcon', 5)}",
        f"NL%ISOILCOL = {as_int(row, 'isoilcol', 21)}",
        f"NL%SLXCLAY = {as_float(row, 'slxclay', 0.0):.10g}",
        f"NL%SLXSAND = {as_float(row, 'slxsand', 0.0):.10g}",
        f"NL%SLSOC = {as_float(row, 'slsoc', 0.0):.10g}",
        f"NL%SLPH = {as_float(row, 'slph', 7.0):.10g}",
        f"NL%SLCEC = {as_float(row, 'slcec', 0.0):.10g}",
        f"NL%SLDBD = {as_float(row, 'sldbd', 1200.0):.10g}",
        f"NL%SLZ = {nml_list(row['slz'])}",
        f"NL%SLMSTR = {nml_list(row['slmstr'])}",
        f"NL%STGOFF = {nml_list(row['stgoff'])}",
        f"NL%SOIL_HYDRO_SCHEME = {as_int(row, 'soil_hydro_scheme', 0)}",
        f"NL%ISOILBC = {as_int(row, 'isoilbc', 1)}",
        f"NL%SLDRAIN = {as_float(row, 'sldrain', 0.0):.10g}",
        f"NL%ISOILSTATEINIT = {as_int(row, 'isoilstateinit', 0)}",
        f"NL%ISOILDEPTHFLG = {as_int(row, 'isoildepthflg', 0)}",
    ]
    write_text(output / "fragments" / "ed2in_soil_fragment.nml", "\n".join(lines) + "\n", manifest)


def convert_met(staging: Path, output: Path, met_prefix: str, manifest: list[Path]) -> Path | None:
    met_csv = staging / "met.csv"
    if not met_csv.exists():
        return None
    met_output = output / "met"
    converter = REPO_ROOT / "scripts" / "csv_to_ed2_met.py"
    subprocess.run([sys.executable, str(converter), str(met_csv), str(met_output), "--prefix", met_prefix], check=True)
    for produced in sorted(met_output.glob("*")):
        manifest.append(produced)
    return met_output / "ED_MET_DRIVER_HEADER"


def write_month_table(rows: list[dict[str, str]], destination: Path, manifest: list[Path]) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", newline="\n") as handle:
        for row in rows:
            missing = [name for name in ("lat", "lon", *MONTH_COLUMNS) if row.get(name, "") == ""]
            if missing:
                raise SystemExit(f"Missing columns for {destination}: {', '.join(missing)}")
            values = [row["lat"], row["lon"], *(row[month] for month in MONTH_COLUMNS)]
            handle.write(" ".join(values) + "\n")
    manifest.append(destination)


def build_ed_inputs(staging: Path, output: Path, manifest: list[Path]) -> bool:
    wrote_any = False
    chd = optional_rows(staging / "thermal_sums_chd.csv")
    if chd:
        write_month_table(chd, output / "ed_inputs" / "chd" / "temp.chd.avg.dat", manifest)
        wrote_any = True
    dgd = optional_rows(staging / "thermal_sums_dgd.csv")
    if dgd:
        write_month_table(dgd, output / "ed_inputs" / "dgd" / "temp.dgd.avg.dat", manifest)
        wrote_any = True
    plantation = optional_rows(staging / "plantation_fraction.csv")
    if plantation:
        destination = output / "ed_inputs" / "fraction.plantation"
        destination.parent.mkdir(parents=True, exist_ok=True)
        with destination.open("w", newline="\n") as handle:
            handle.write("lat lon fracplant\n")
            for row in plantation:
                handle.write(f"{row['lat']} {row['lon']} {row['fracplant']}\n")
        manifest.append(destination)
        wrote_any = True
    return wrote_any


def build_phenology(staging: Path, output: Path, region_info: dict[str, str], manifest: list[Path]) -> Path | None:
    rows = optional_rows(staging / "phenology_prescribed.csv")
    if not rows:
        return None
    grouped: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        missing = [name for name in ("lat", "lon", "year", "flush_a", "flush_b", "color_a", "color_b") if row.get(name, "") == ""]
        if missing:
            raise SystemExit(f"phenology_prescribed.csv is missing: {', '.join(missing)}")
        grouped[(row["lat"], row["lon"])].append(row)

    phen_dir = output / "phenology"
    phen_dir.mkdir(parents=True, exist_ok=True)
    for (lat, lon), items in sorted(grouped.items()):
        name = f"phenology.lat{format_coord(lat)}lon{format_coord(lon)}.txt"
        destination = phen_dir / name
        with destination.open("w", newline="\n") as handle:
            handle.write(f"{len(items)}\n")
            for row in sorted(items, key=lambda item: int(float(item["year"]))):
                handle.write(
                    f"{row['year']} {row['flush_a']} {row['flush_b']} {row['color_a']} {row['color_b']}\n"
                )
        manifest.append(destination)

    years = [int(float(row["year"])) for row in rows]
    lines = [
        "! Generated prescribed-phenology fragment",
        "NL%IPHEN_SCHEME = 1",
        f"NL%IPHENYS1 = {min(years)}",
        f"NL%IPHENYSF = {max(years)}",
        f"NL%IPHENYF1 = {min(years)}",
        f"NL%IPHENYFF = {max(years)}",
        "NL%PHENPATH = '@PHENPATH@'",
    ]
    fragment = output / "fragments" / "ed2in_phenology_fragment.nml"
    write_text(fragment, "\n".join(lines) + "\n", manifest)
    return phen_dir / "phenology"


def write_plain_rows(rows: list[dict[str, str]], destination: Path, columns: tuple[str, ...], manifest: list[Path]) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", newline="\n") as handle:
        handle.write(" ".join(columns) + "\n")
        for row in rows:
            missing = [name for name in columns if row.get(name, "") == ""]
            if missing:
                raise SystemExit(f"{destination.name}: missing columns: {', '.join(missing)}")
            handle.write(" ".join(row[name] for name in columns) + "\n")
    manifest.append(destination)


def build_ed22_initial(
    staging: Path,
    output: Path,
    region_name: str,
    region_info: dict[str, str],
    manifest: list[Path],
) -> Path | None:
    sites = optional_rows(staging / "ed22_sites.csv")
    patches = optional_rows(staging / "ed22_patches.csv")
    cohorts = optional_rows(staging / "ed22_cohorts.csv")
    if not sites and not patches and not cohorts:
        return None
    if not (sites and patches and cohorts):
        raise SystemExit("ED2.2 initial files require all three: ed22_sites.csv, ed22_patches.csv, ed22_cohorts.csv")

    lat = format_coord(region_info["poi_lat"])
    lon = format_coord(region_info["poi_lon"])
    prefix_name = f"{region_name}.lat{lat}lon{lon}"
    init_dir = output / "inits"
    write_plain_rows(
        sites,
        init_dir / f"{prefix_name}.sss",
        (
            "sname",
            "area",
            "depth",
            "nscol",
            "ntext",
            "sand",
            "clay",
            "slsoc",
            "slph",
            "slcec",
            "sldbd",
            "elevation",
            "slope",
            "aspect",
            "tci",
            "moist_f",
            "moist_w",
        ),
        manifest,
    )
    write_plain_rows(
        patches,
        init_dir / f"{prefix_name}.pss",
        (
            "time",
            "sname",
            "pname",
            "dtype",
            "age",
            "area",
            "fgc",
            "fsc",
            "stgc",
            "stgl",
            "stsc",
            "stsl",
            "msc",
            "ssc",
            "psc",
            "fsn",
            "msn",
            "dummy1",
            "dummy2",
            "dummy3",
            "dummy4",
        ),
        manifest,
    )
    write_plain_rows(
        cohorts,
        init_dir / f"{prefix_name}.css",
        (
            "time",
            "sname",
            "pname",
            "cname",
            "dbh",
            "height",
            "pft",
            "nplant",
            "bdead",
            "balive",
            "dummy1",
            "dummy2",
        ),
        manifest,
    )
    fragment = output / "fragments" / "ed2in_ed22_initial_fragment.nml"
    lines = [
        "! Generated ED2.2 text-initialisation fragment",
        "NL%IED_INIT_MODE = 8",
        "NL%SFILIN = '@SFILIN@'",
    ]
    write_text(fragment, "\n".join(lines) + "\n", manifest)
    return init_dir / f"{region_name}."


def replace_fragment_placeholders(output: Path, replacements: dict[str, str]) -> None:
    for path in sorted((output / "fragments").glob("*.nml")):
        text = path.read_text(encoding="utf-8")
        for key, value in replacements.items():
            text = text.replace(key, value)
        path.write_text(text, encoding="utf-8")


def build_paths_fragment(
    output: Path,
    manifest: list[Path],
    met_header: Path | None,
    has_ed_inputs: bool,
    phen_prefix: Path | None,
    init_prefix: Path | None,
    ed_run_dir: Path,
    absolute_paths: bool,
) -> None:
    def maybe_path(path: Path | None) -> str:
        return "" if path is None else path_for_namelist(path, ed_run_dir, absolute_paths)

    ed_inputs_dir = output / "ed_inputs"
    plantation = ed_inputs_dir / "fraction.plantation"
    lines = [
        "! Generated ED2 input-path fragment",
        "NL%VEG_DATABASE = ''",
        "NL%SOIL_DATABASE = ''",
        "NL%SLCOL_DATABASE = ''",
        "NL%LU_DATABASE = ''",
        f"NL%PLANTATION_FILE = {nml_string(maybe_path(plantation if plantation.exists() else None))}",
        f"NL%THSUMS_DATABASE = {nml_string(maybe_path(ed_inputs_dir if has_ed_inputs else None))}",
        f"NL%ED_MET_DRIVER_DB = {nml_string(maybe_path(met_header))}",
        "NL%OBSTIME_DB = ''",
        "NL%SOILSTATE_DB = ''",
        "NL%SOILDEPTH_DB = ''",
    ]
    if init_prefix is not None:
        lines.append(f"NL%SFILIN = {nml_string(maybe_path(init_prefix))}")
    write_text(output / "fragments" / "ed2in_input_paths_fragment.nml", "\n".join(lines) + "\n", manifest)

    replacements = {
        "'@PHENPATH@'": nml_string(maybe_path(phen_prefix)),
        "'@SFILIN@'": nml_string(maybe_path(init_prefix)),
    }
    replace_fragment_placeholders(output, replacements)


def write_manifest(output: Path, manifest: list[Path]) -> None:
    unique = []
    seen = set()
    for path in manifest:
        if path not in seen:
            unique.append(path)
            seen.add(path)
    text = ["# ED2 staged build manifest", ""]
    text.extend(str(path) for path in unique)
    (output / "MANIFEST.txt").write_text("\n".join(text) + "\n", encoding="utf-8")


def build(args: argparse.Namespace) -> int:
    args.output.mkdir(parents=True, exist_ok=True)
    manifest: list[Path] = []
    region_name = args.region_name
    region_info = build_domain_fragment(args.staging, args.output, region_name, manifest)
    build_soil_fragment(args.staging, args.output, manifest)
    met_prefix = args.met_prefix or region_info["met_prefix"]
    met_header = convert_met(args.staging, args.output, met_prefix, manifest)
    has_ed_inputs = build_ed_inputs(args.staging, args.output, manifest)
    phen_prefix = build_phenology(args.staging, args.output, region_info, manifest)
    init_prefix = build_ed22_initial(args.staging, args.output, region_name, region_info, manifest)
    build_paths_fragment(
        args.output,
        manifest,
        met_header,
        has_ed_inputs,
        phen_prefix,
        init_prefix,
        args.ed_run_dir,
        args.absolute_paths,
    )
    write_manifest(args.output, manifest)
    print(f"wrote {args.output / 'MANIFEST.txt'}")
    return 0


def make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init", help="Copy CSV templates into a staging directory.")
    init_parser.add_argument("target", type=Path)
    init_parser.add_argument("--force", action="store_true", help="Overwrite existing template files.")
    init_parser.set_defaults(func=copy_templates)

    build_parser = subparsers.add_parser("build", help="Build ED2-ready files from a staging directory.")
    build_parser.add_argument("staging", type=Path)
    build_parser.add_argument("output", type=Path)
    build_parser.add_argument("--region-name", default="region", help="Short safe name used in generated filenames.")
    build_parser.add_argument("--met-prefix", help="Override met HDF5 file prefix.")
    build_parser.add_argument("--ed-run-dir", type=Path, default=REPO_ROOT / "ED" / "run")
    build_parser.add_argument("--absolute-paths", action="store_true", help="Write absolute paths in ED2IN fragments.")
    build_parser.set_defaults(func=build)
    return parser


def main() -> int:
    args = make_parser().parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
